# action.yml
name: 'Maven release'
author: https://github.com/qcastel
description: 'Release your java application'
branding:
  color: blue
  icon: unlock
inputs:
  release-branch-name:
    description: 'Filter the branch to execute the release on'
    required: false

  maven-local-repo-path: 
    description: 'The maven local repository path'
    required: false
    default: '$M2_HOME/repository'
  maven-repo-server-id:
    description: 'Maven server repository id to push the artefacts to'
    required: true
  maven-repo-server-username:
    description: 'Maven server repository username'
    required: true
  maven-repo-server-password:
    description: 'Maven server repository password'
    required: true
  maven-release-args:
    description: 'The maven arguments for the release step'
    required: true
    default: ''
  maven-build-release-args:
    description: 'The maven arguments for the build release step'
    required: true
    default: ''
  maven-project-folder:
    description: 'You may have more than one maven projects inside the repo. This option allows you to specify the folder for which you want to trigger the release'
    required: false
    default: './'
  git-release-bot-name:
    description: 'The git user name for commiting the release'
    required: true
  git-release-bot-email:
    description: 'The git user email for commiting the release'
    required: true
  skip-perform:
    description: 'Skip maven release perform'
    required: false
    default: false

      
  access-token:
    description: 'Github access token. https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - release.sh
  env:
    RELEASE_BRANCH_NAME: ${{ inputs.release-branch-name }}

    MAVEN_LOCAL_REPO_PATH: ${{ inputs.maven-local-repo-path }}
    MAVEN_REPO_SERVER_ID: ${{ inputs.maven-repo-server-id }}
    MAVEN_REPO_SERVER_USERNAME: ${{ inputs.maven-repo-server-username }}
    MAVEN_REPO_SERVER_PASSWORD: ${{ inputs.maven-repo-server-password }}
    MAVEN_PROJECT_FOLDER: ${{ inputs.maven-project-folder }}
    MAVEN_RELEASE_ARGS: ${{ inputs.maven-release-args }}
    $MAVEN_BUILD_RELEASE_ARGS: ${{ inputs.maven-release-build-args }}

    SKIP_PERFORM: ${{ inputs.skip-perform }}

    GIT_RELEASE_BOT_NAME: ${{ inputs.git-release-bot-name }}
    GIT_RELEASE_BOT_EMAIL: ${{ inputs.git-release-bot-email }}

    GITHUB_ACCESS_TOKEN: ${{ inputs.access-token }}
